### ISSUE TITLE
ImportError: cannot import name 'BOOLEAN_STATES'

### ISSUE THREAD

**Issue by dand-oss** [pybpc/walrus#21]
pip install python-walrus
walrus

Traceback (most recent call last):
  File "/i/t/pypy/bin/walrus", line 5, in <module>
    from walrus import main
  File "/i/t/pypy/site-packages/walrus.py", line 13, in <module>
    from bpc_utils import BOOLEAN_STATES, CPU_CNT, LOCALE_ENCODING, UUID4Generator, archive_files, detect_files, mp
ImportError: cannot import name 'BOOLEAN_STATES'

**Comment by gousaiyang** [comment]
Hello! Thanks for using `walrus`. We were sorry to break compatibility with our internal utility library during the current refactoring of the project. Before we cut a new release, you can try out the following ways to use `walrus`:

- Try using the current master branch (`git clone` then `pip install .`)
- Try to revert to `walrus` v0.1.3

Thanks!
